-- Buat tabel tables
CREATE TABLE tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'inactive' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert beberapa data awal meja
INSERT INTO tables (number, status) VALUES 
('Meja 1', 'active'),
('Meja 2', 'active'),
('Meja 3', 'active'),
('Meja 4', 'active'),
('Meja 5', 'active');

-- Tambahkan RLS (Row Level Security) jika diperlukan
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;

-- Izinkan semua orang membaca status meja
CREATE POLICY "Allow public read access" ON tables
  FOR SELECT USING (true);

-- Izinkan admin mengubah status meja (berdasarkan auth.uid())
CREATE POLICY "Allow admin to update" ON tables
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Tambahkan kolom baru ke tabel menu untuk detail produk
ALTER TABLE menu ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE menu ADD COLUMN IF NOT EXISTS ingredients TEXT;
ALTER TABLE menu ADD COLUMN IF NOT EXISTS serving_style TEXT;
ALTER TABLE menu ADD COLUMN IF NOT EXISTS sugar_levels JSONB DEFAULT '["Normal", "Less Sugar", "No Sugar"]'::jsonb;
ALTER TABLE menu ADD COLUMN IF NOT EXISTS sizes JSONB DEFAULT '["Regular", "Large"]'::jsonb;
ALTER TABLE menu ADD COLUMN IF NOT EXISTS has_options BOOLEAN DEFAULT FALSE;

-- Tambahkan instruksi untuk membuat bucket storage (Harus dijalankan di Dashboard Supabase atau API)
/*
  1. Buka Dashboard Supabase -> Storage
  2. Klik "New bucket"
  3. Beri nama: "menu-images"
  4. Centang "Public bucket" agar gambar bisa diakses publik
*/

-- Kebijakan Storage (Jalankan di SQL Editor Supabase jika bucket sudah dibuat)
-- Izinkan akses publik untuk membaca gambar
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'menu-images');

-- Izinkan admin yang terautentikasi untuk mengunggah gambar
CREATE POLICY "Admin Upload" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'menu-images' AND auth.role() = 'authenticated'
);

-- Izinkan admin untuk menghapus gambar
CREATE POLICY "Admin Delete" ON storage.objects FOR DELETE USING (
  bucket_id = 'menu-images' AND auth.role() = 'authenticated'
);


